name: Create a GitHub Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
